# Generated by Django 5.2.10 on 2026-01-25 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(blank=True, default='avatars/default.png', help_text='Profile picture (recommended: 200x200 pixels)', null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself (max 500 characters)', max_length=500)),
                ('location', models.CharField(blank=True, help_text="Your location (e.g., 'New York, USA')", max_length=100)),
                ('website', models.URLField(blank=True, help_text='Your personal website URL')),
                ('twitter', models.CharField(blank=True, help_text='Twitter username (without @)', max_length=50)),
                ('github', models.CharField(blank=True, help_text='GitHub username', max_length=50)),
                ('linkedin', models.CharField(blank=True, help_text='LinkedIn profile URL or username', max_length=100)),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications for comments on your posts')),
                ('is_public', models.BooleanField(default=True, help_text='Make your profile visible to other users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
