# Generated by Django 5.2.10 on 2026-01-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="Subscriber's email address", max_length=254, unique=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Email has been verified')),
                ('is_active', models.BooleanField(default=True, help_text='Subscription is active')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('#4f46e5', 'Indigo'), ('#2563eb', 'Blue'), ('#0891b2', 'Cyan'), ('#059669', 'Green'), ('#84cc16', 'Lime'), ('#eab308', 'Yellow'), ('#f97316', 'Orange'), ('#ef4444', 'Red'), ('#ec4899', 'Pink'), ('#8b5cf6', 'Purple'), ('#6366f1', 'Violet'), ('#64748b', 'Slate')], default='#4f46e5', help_text='Color for category badge and default image', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('bi-laptop', 'Technology'), ('bi-globe', 'Web Development'), ('bi-code-slash', 'Programming'), ('bi-graph-up', 'Data Science'), ('bi-mortarboard', 'Tutorial'), ('bi-newspaper', 'News'), ('bi-camera', 'Photography'), ('bi-palette', 'Design'), ('bi-briefcase', 'Business'), ('bi-heart', 'Lifestyle'), ('bi-airplane', 'Travel'), ('bi-cup-hot', 'Food'), ('bi-controller', 'Gaming'), ('bi-music-note', 'Music'), ('bi-film', 'Entertainment'), ('bi-book', 'Education'), ('bi-lightbulb', 'Ideas'), ('bi-chat-quote', 'Opinion')], default='bi-newspaper', help_text='Bootstrap icon for this category', max_length=50),
        ),
    ]
